# Generated by Django 2.1.3 on 2018-11-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField(default=0)),
                ('race_date', models.DateTimeField(blank=True, null=True)),
                ('horse_id', models.IntegerField(unique=True)),
                ('jockey_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('horse_weight', models.CharField(max_length=200)),
                ('track_type', models.CharField(max_length=200)),
                ('distance', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('horse_name', models.CharField(max_length=200)),
                ('horse_age', models.CharField(max_length=200)),
                ('horse_father_id', models.IntegerField(default=-1)),
                ('horse_mother_id', models.IntegerField(default=-1)),
                ('order', models.IntegerField(default=-1)),
                ('result', models.IntegerField(default=-1)),
                ('handicap', models.IntegerField(default=-1)),
                ('time', models.CharField(default=-1, max_length=200)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
